config/routes.rb
Rails.application.routes.draw do
  root to: 'series#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :words
  resources :series do
    member do
      get :database
    end

    resources :chapters do
      resources :episodes
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :series
  has_many :episodes, dependent: :destroy
  has_many :words, through: :episodes
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :chapter
  has_many :words, dependent: :destroy

  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end
end

app/models/series.rb
class Series < ApplicationRecord
  has_many :chapters, dependent: :destroy
  has_many :episodes, through: :chapters
  has_many :words, through: :episodes
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :episode

  include PgSearch::Model
  pg_search_scope :word_search,
                  against: %i[word reading definition level],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @chapters = Chapter.includes(:series)
  end

  def show
    @chapter = Chapter.find(params[:id])
    @episodes = Episode.all
    @series = Series.find(params[:series_id])
    @chapter.series = @series
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
    @episodes = Episode.includes(:chapter)
  end

  def show
    @episode = Episode.find(params[:id])
    @chapter = Chapter.find(params[:chapter_id])
    @series = Series.find(params[:series_id])
    @chapter.series = @series
    @words = Word.all
    @episodes = Episode.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  WORDS_PER_PAGE = 50
  def index
    @series = Series.all
  end

  def show
    @series = Series.find(params[:id])
    @chapters = Chapter.all
  end

  def database
    @series = Series.find(params[:id])
    @page = params.fetch(:page, 0).to_i
    @database = @series.words.offset(@page * WORDS_PER_PAGE).limit(WORDS_PER_PAGE)
    @total_series_words = @series.words.size
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    if params[:query].present?
      @words = Word.word_search(params[:query])
    else
      @words = Word.includes(:episode, :chapter, :series)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/show.html.erb
<h1 class="m-3 text-center"><%= @chapter.name %></h1>

<div class="cards">
  <% @chapter.episodes.each do |episode| %>
    <% image = "https://img.youtube.com/vi/#{episode.youtube_id}/maxresdefault.jpg" %>
    <%= link_to series_chapter_episode_path(@series, @chapter, episode) do %>
     <div class="card-episode" style="background-image: url(<%= image %>)">
</div>
    <% end %>
  <% end %>
</div>

app/views/episodes/show.html.erb
<h1 class="m-3 text-center"><%= @episode.name %></h1>

<div style="justify-content: center; display: flex;">

  <% video_id = "https://www.youtube.com/embed/#{@episode.youtube_id}" %>

  <iframe width="720" height="405" src=<%= video_id %> frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<div class="nav-links">
    <% if @episode.id > 1 %>
      <%= link_to series_chapter_episode_path(@series, @chapter, @episode.previous) do %>
        <i class="fas fa-arrow-left"></i> Previous
      <% end %>
    <% else %>
      <span style="opacity: 0"><i class="fas fa-arrow-left"></i> Previous</span>
    <% end %>

    <p class="vocab"><%= @episode.words.size %> words</p>

    <% if @episode.id < @episodes.size %>
      <%= link_to series_chapter_episode_path(@series, @chapter, @episode.next) do %>
        Next <i class="fas fa-arrow-right"></i>
      <% end %>
    <% else %>
      <span style="opacity: 0">Next <i class="fas fa-arrow-right"></i></span>
    <% end %>
</div>


<div class="scrollable">
  <table>
    <thead>
      <tr>
        <th style="width: 15%;position: -webkit-sticky;position: sticky;top: 0; background: #00252d">Word</th>
        <th style="width: 15%;position: -webkit-sticky;position: sticky;top: 0; background: #00252d">Reading</th>
        <th style="width: 55%;position: -webkit-sticky;position: sticky;top: 0; background: #00252d">Definition</th>
        <th style="width: 15%;position: -webkit-sticky;position: sticky;top: 0; background: #00252d">JLPT level</th>
      </tr>
    </thead>

    <tbody>
      <% @episode.words.each do |word| %>
        <tr>
          <td><%= word.word %></td>
          <td><%= word.reading %></td>
          <td><%= word.definition %></td>
          <td><%= word.level %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameGengo</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>

  <div class="d-flex flex-column min-vh-100">
    <%= render 'shared/navbar' %>
    <div class="container flex-grow-1">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/series/database.html.erb
<h3 class="m-3 text-center">Vocabulary - <%= @total_series_words %> words</h3>

<%= form_tag words_path, method: :get do %>
<%= text_field_tag :query,
params[:query],
class: "form-control",
  placeholder: "Search by word or JLPT level"
  %>
  <%= submit_tag "Search", class: "btn btn-light" %>
  <% end %>

  <table class="center">
    <thead>
      <tr>
        <th style="width: 100px;">Chapter</th>
        <th style="width: 100px;">Episode</th>
        <th style="width: 100px;">Word</th>
        <th style="width: 100px;">Reading</th>
        <th style="width: 300px;">Definition</th>
        <th style="width: 100px;">JLPT level</th>
      </tr>
    </thead>

    <tbody>
      <% @database.each do |word| %>
      <tr>
        <%= link_to series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode) do  %>
        <td><%= link_to word.episode.chapter.id, series_chapter_path(word.episode.chapter.series, word.episode.chapter)  %></td>
        <td><%= link_to word.episode.id, series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode)  %></td>
        <td><%= link_to word.word, series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode)  %></td>
        <% if word.reading.present? %>
        <td><%= link_to word.reading, series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode)  %></td>
        <% else %>
        <td><%= word.reading %> </td>
        <% end %>
        <td><%= link_to word.definition, series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode)  %></td>
        <td><%= link_to word.level, series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode)  %></td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>



  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <li class="page-item">
        <% if @page > 0 %>
          <%= link_to "Previous page", database_series_path(page: @page - 1), class: 'page-link' %>
        <% end %>
      </li>
      <li class="page-item">
        <%= link_to "Next page", database_series_path(page: @page + 1), class: 'page-link' %>
      </li>
    </ul>
  </nav>

app/views/series/index.html.erb
<h1 class="m-3 text-center">Choose Your Series</h1>


<% @series.each do |series| %>
  <%= link_to series_path(series) do %>
    <div class="card-series" style="background-image: url('https://ffvii-remake.square-enix-games.com/share-images/SEA_END_fb_share_img_1200x630.jpg')">
    </div>
  <% end %>
<% end %>

app/views/series/show.html.erb
<h1 class="m-3 text-center"><%= @series.name %></h1>

<% @chapters.each do |chapter| %>
  <%= link_to series_chapter_path(@series, chapter) do %>
    <div class="card-chapter" style="background-image: url(<%= chapter.image_url %>)">
      <%= chapter.name %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.facebook.com/GameGengo/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/gamegengo"><i class="fab fa-twitter"></i></a>
    <a href="https://www.instagram.com/gamegengo/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.patreon.com/GameGengo"><i class="fab fa-patreon"></i></a>
    <a href="https://www.youtube.com/channel/UCsXJuG5tSNRr9IwfjMbNvqQ"><i class="fab fa-youtube"></i></a>
  </div>
  <div class="footer-copyright">
  Game Gengo 2021
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "https://yt3.ggpht.com/ytc/AAUvwngdbEhJoOjRKMztc0VR5SiHJQ1Kbx3kRoEibTBV=s900-c-k-c0x00ffffff-no-rj", id: "logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-link">
        <%= link_to "Home", series_index_path %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Series
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% Series.all.each do |series| %>
          <%= link_to series.name, series_path(series), class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Database
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% Series.all.each do |series| %>
          <%= link_to series.name, database_series_path(series), class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a href="https://www.patreon.com/GameGengo"><button class="btn btn-sm btn-outline-light" type="button">Join Patreon</button></a>
      </li>
    </ul>

  </div>
</nav>

app/views/words/index.html.erb
<h3 class="m-3 text-center">Vocabulary - <%= @words.count %> words</h3>

<%= form_tag words_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search by word or JLPT level"
  %>
  <%= submit_tag "Search", class: "btn btn-light" %>
<% end %>

<table class="center">
  <thead>
    <tr>
      <th style="width: 100px;">Chapter</th>
      <th style="width: 100px;">Episode</th>
      <th style="width: 100px;">Word</th>
      <th style="width: 100px;">Reading</th>
      <th style="width: 300px;">Definition</th>
      <th style="width: 100px;">JLPT level</th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
    <%= link_to series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode) do  %>
        <td><%= link_to word.episode.chapter.id, series_chapter_path(word.episode.chapter.series, word.episode.chapter)  %></td>
        <td><%= link_to word.episode.id, series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode)  %></td>
        <td><%= link_to word.word, series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode)  %></td>
        <% if word.reading.present? %>
          <td><%= link_to word.reading, series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode)  %></td>
          <% else %>
          <td><%= word.reading %> </td>
          <% end %>
        <td><%= link_to word.definition, series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode)  %></td>
        <td><%= link_to word.level, series_chapter_episode_path(word.episode.chapter.series, word.episode.chapter, word.episode)  %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>